export const ADD_ORDERDB_REQUEST = "ADD_ORDERDB_REQUEST"
export const ADD_ORDERDB_SUCCESS = "ADD_ORDERDB_SUCCESS"
export const ADD_ORDERDB_FAIL = "ADD_ORDERDB_FAIL"

export const SHOW_ORDERS_REQUEST = "SHOW_ORDERS_REQUEST"
export const SHOW_ORDERS_SUCCESS = "SHOW_ORDERS_SUCCESS"
export const SHOW_ORDERS_FAIL = "SHOW_ORDERS_FAIL"