export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"

export const PRODUCT_CREATOR_REQUEST = "PRODUCT_CREATOR_REQUEST"
export const PRODUCT_CREATOR_UPDATE = "PRODUCT_CREATOR_UPDATE"
export const PRODUCT_CREATOR_DELETE = "PRODUCT_CREATOR_DELETE"
export const PRODUCT_CREATOR_CREATED = "PRODUCT_CREATOR_CREATED"
export const PRODUCT_CREATOR_FAIL = "PRODUCT_CREATOR_FAIL"

export const REVIEW_ADD_REQUEST = "REVIEW_ADD_REQUEST"
export const REVIEW_ADD_SUCCESS = "REVIEW_ADD_SUCCESS"
export const REVIEW_ADD_FAIL = "REVIEW_ADD_FAIL"

export const SORT_BY_REQUEST = "SORT_BY_REQUEST"
export const SORT_BY_PRICE = "SORT_BY_PRICE"
export const SORT_BY_DATE = "SORT_BY_DATE"
export const SORT_BY_ERROR = "SORT_BY_ERROR"
export const SHOW_SEARCH_REQUEST = "SHOW_SEARCH_REQUEST"
export const SHOW_SEARCH_SUCCESS = "SHOW_SEARCH_SUCCESS"
export const SHOW_SEARCH_FAIL = "SHOW_SEARCH_FAIL"



export const CART_ADD_LOADING = "CART_ADD_LOADING"
export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_ADD_FAIL = "CART_ADD_FAIL"

//hemos perdido media hora por dejar pueso CART_DELETE_ITEM = "CART_DELETE_ITEM"
//fallo que además te quedas wtf xq la app edja de tener sentdio
export const CART_DELETE_ITEM= "CART_DELETE_ITEM"
export const CART_UPDATE_ITEM = "CART_UPDATE_ITEM"
