export const USER_LOGIN_REQUEST = "USER_LOGGING_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGGING_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGGING_FAIL"


export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"